### ISSUE TITLE
Uglify task works not correctly

### ISSUE THREAD

**Issue by flovogt** [SAP/ui5-builder#283]
Hi team,
during development of an sample app. I found following issue with the uglify task.

## Expected Behavior
Uglify task works correctly

## Current Behavior
Variable contains not the correct value

## Context
- UI5 Module Version: 1.5.5
- Node.js Version: 10.11.0
- npm Version: 6.4.1
- OS/Platform: windows

## Steps
1. Run the build with `uglify` task
2. Run the app with `npm run serve:dist`
3. Open the browser
4. Click on the first tile
5. Click on the first list item
6. Have a look in the console -> error is thrown. var `p` contains not the correct value

## Affected components *(if known)*
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by codeworrior** [comment]
Hi Florian!

did you maybe intend to point us to the sample app? Or attach it? Without, it is too hard to analyze this...

**Comment by flovogt** [comment]
Hi Frank,
I have sent the link to @matz3 and @RandomByte in a direct message. I‘ll sent it also to you.

**Comment by codeworrior** [comment]
This is not an issue of the bundler but of the FHIR model. The module `FHIRRequestor.js` contains the following code:

```js
      h.prototype._getBundleByGroup = function(e) {
        var t = this._mBundleQueue[e];
        if (!t) {
          t = new n(this._getBundleTypeBySubmitMode(this._getGroupSubmitMode(e)),e)
        } else if (t.constructor.name === "RequestHandle") {
          t = t.getBundle()
        }
        return t
      }
```

The check for the `t.constructor.name` does not survive minification. Detecting that such generic code is affected by a variable renaming is (in JavaScript) by far too difficult for static code transformation tools like uglify. An easy way out should be to use `RequestHandle.name` instead of the literal string (it is affected by the renaming in the same way). 

But in general, coding against names of functions is IMO risky as it e.g. prevents subclassing. Why was an `instanceof` check not suitable?

**Comment by flovogt** [comment]
@codeworrior Thanks a lot for clarification. We‘ll provide a fix for that.

**Comment by flovogt** [comment]
resolved with https://github.com/SAP/openui5-fhir/pull/31/

**Comment by flovogt** [comment]
Hi @codeworrior,
for the preload build your proposal was sufficient. The self contained build is still failing.
```javascript
 a._filterBuilder = function(t, i, n, a, s) {
                var f = t.sPath;
                var u = e.getFHIRSearchParameterModifier(t);
                var o = e.getFilterValue(t.oValue1);
                var c = e.getFHIRSearchPrefix(t);
```

The var `e` is not defined. So, `"sap/fhir/model/r4/FHIRFilterOperatorUtils",` can not be loaded from the `sap/fhir/model/r4/FHIRUtils.js` in the `sap-ui-custom.js`. Can you give us guidenance what we're doing wrong?

**Comment by codeworrior** [comment]
Undefined values for dependencies sounds like an issue with cyclic dependencies. Maybe you should take a look at https://openui5nightly.hana.ondemand.com/#/topic/4363b3fe3561414ca1b030afc8cd30ce, esp. the paragraph about cyclic dependencies.

In your case, one cycle is  [FHIRFilterOperatorUtils.js](https://github.com/SAP/openui5-fhir/blob/master/src/sap/fhir/model/r4/FHIRFilterOperatorUtils.js) <--> [FHIRUtils.js](https://github.com/SAP/openui5-fhir/blob/master/src/sap/fhir/model/r4/FHIRUtils.js) . 

Cycles become more obvious when async loading is used. Maybe that's why they show up only now.

**Comment by flovogt** [comment]
Hi @codeworrior, thanks a lot. Would it be possible to print a message inside the build that there is a cyclic dependency? It's quite hard to find out that this was the issue. Thanks.

**Comment by codeworrior** [comment]
We considered this but decided against it as cycles _can_ be okay, _if you deal with them_. It's not easily possible to find the latter out in the tooling.

But I guess we have to reconsider this...

**Comment by flovogt** [comment]
So at the moment there is no way to get be informed if someone implemented a cyclic dependency?

**Comment by codeworrior** [comment]
[codeworrior] "yes...." _(abashed)_

**Comment by flovogt** [comment]
thx
