### ISSUE TITLE
Norwgian characters are being corrupted in Component-preload.js

### ISSUE THREAD

**Issue by mvoros** [SAP/ui5-builder#290]
### Expected Behaviour

The special characters from Norwegian language do not get corrupted in Component-preload.js

### Current Behavior

We have a UI5 app with text in Norwegian. E.g. we have a property file i18n_no.properties with text title=Årsplan. The problem is that when a Component-preload.js is generated, the result looks like title=Ãrsplan. There is an additional unicode character. This additional character then shows up in the app. 

### Affected components

This issue is present with UI5-Cli version 1.6.0.

**Comment by codeworrior** [comment]
Most likely this is caused by the fact that you stored your i18n_no.properties in UTF-8. UI5 and its tooling expect the files to be encoded in ISO8859-1. 

We're currently considering a configuration option to also support other encodings for *.properties files, but as long as this is not active, you can either use the ISO8859-1 encoding or \unnnn encode any non-ASCII characters.

**Comment by mvoros** [comment]
OK. I can confirm that maintaining the property file with escape codes. (e.g. title=\u00C5rsplan) works fine. it would be nice to have a preprocessing step that converts all property files by replacing all unicode character with escape codes. Now we have to do it manually for each file but luckily there are some online tools that do this.

**Comment by matz3** [comment]
Also see https://github.com/SAP/ui5-tooling/pull/168

**Comment by RandomByte** [comment]
With UI5 CLI [`v1.7.0`](https://github.com/SAP/ui5-cli/releases/tag/v1.7.0), you can now configure `UTF-8` as the source encoding of a projects `*.properties` files. The default stays at `ISO-8859-1`. In both cases the UI5 Tooling will escape any non-ASCII characters, so that the build result is independent from the encoding.

📖 [Documentation](https://sap.github.io/ui5-tooling/pages/Configuration/#resources-optional) (see `propertiesFileSourceEncoding`)  
🔎 [Demo](https://github.com/SAP/openui5-sample-app/pull/54)
