### ISSUE TITLE
Available tasks for the builder?

### ISSUE THREAD

**Issue by Kritten** [SAP/ui5-builder#374]
## Expected Behavior
https://sap.github.io/ui5-tooling/pages/Builder/lib/tasks should list the tasks
https://sap.github.io/ui5-tooling/pages/Builder/lib/processors should list the processors

## Current Behavior
Both links show a 404 error page

## Steps to reproduce the issue
1. Go to one of the mentioned links

## Notes
I wanted to know what the `generateManifestBundle` option does and whether I really need the generated manifest-bundle.zip

**Comment by RandomByte** [comment]
Hey thanks for reporting! Where did you find those links? Looks like they need to be corrected. I guess they should point to the following:  
- https://sap.github.io/ui5-tooling/api/module-@ui5_builder.tasks.html
- https://sap.github.io/ui5-tooling/api/module-@ui5_builder.processors.html

**Comment by Kritten** [comment]
Oh wow you're fast :)
I found them on the homepage: https://sap.github.io/ui5-tooling/pages/Builder/
You have to click on "Available [tasks|processors] are listed here"

Thank you for the links!

**Comment by RandomByte** [comment]
By default the `generateManifestBundle` task should always be executed if we can detect a namespace for your project. If not, the info `Skipping some tasks due to missing application namespace information. If your project contains a Component.js, you might be missing a manifest.json file.` should be logged and the task will not be executed.

Afaik, it might not even work correctly if no namespace information is available. So you should be able to safely omit the mentioned build parameter.

If you absolutely do not want to execute the task, you may change the parameter to `--exclude-task=generateManifestBundle`.

---

We'll fix the links in the documentation, thanks!

**Comment by RandomByte** [comment]
We should also improve the JSDoc for the generateManifestBundle task. If you are wondering what this task is about, there's this issue that adds some context: https://github.com/SAP/ui5-builder/issues/144

**Comment by vobu** [comment]
hi - any pointers when these fixed links will be available at https://sap.github.io/ui5-tooling/pages/Builder/? The currently broken links once again got me when I tried looking up available tasks :)

**Comment by RandomByte** [comment]
Sorry about that, GitHub deprecated one of their GH-actions libraries by simply deleting it. Took us a while to figure out. Fix is on the way: https://github.com/SAP/ui5-tooling/pull/196

**Comment by RandomByte** [comment]
Fixed
